#!/bin/bash
module load cuda
nvcc -arch=compute_52 -rdc=true -Xcompiler -rdynamic -lineinfo -std=c++11 -O0 -c test.cu -o main.o -lcudadevrt
nvcc -arch=compute_52 -rdc=true -Xcompiler -rdynamic -lineinfo -std=c++11 -O0 -c coredynamics.cu -o coredynamics.o -lcudadevrt
nvcc -arch=compute_52 main.o coredynamics.o -o test
