#include <fstream>
#include <string>
#include <iostream>
#include <cassert>
#include <ctime>
#include <cmath>
#include "condShape.h"
#include "coredynamics.h"
#include "CUDA_MACRO.h"
#include "DIRECTIVE.h"
#include <fenv.h>
