#include <fstream>
#include <string>
#include <iostream>
#include <cassert>
#include <ctime>
#include <cmath>
#include <stdio.h>
#include <fenv.h>
//#include <cuda.h>
#include "DIRECTIVE.h"
#include "CUDA_MACRO.h"
#include "CONST.h"
//#include "connect.h"
#include "cuda_util.h"
#include "coredynamics.h"