#!/bin/bash
module load cuda/9.2
module load boost/gcc_4.9.3/openmpi_1.10.2/avx2/1.57.0
rm -f ext_input.o discrete_convol.o
nvcc -arch=sm_70 -rdc=true -Xcompiler -rdynamic -lineinfo -std=c++11 -g -O0 -c ext_input.cu
nvcc -arch=sm_70 -rdc=true -Xcompiler -rdynamic -lineinfo -std=c++11 -g -O0 -c discrete_input_convol.cu
#nvcc -arch=compute_70 -rdc=true -Xcompiler -rdynamic -lineinfo -std=c++11 -g -O0 -c util/cuda_util.cu
#nvcc -arch=compute_70 -lcudadevrt -lcudart -lboost_program_options ext_input.o discrete_input_convol.o cuda_util.o -o patch #-lcurand
nvcc -arch=sm_70 -lcudadevrt -lcudart -lboost_program_options ext_input.o discrete_input_convol.o -o patch #-lcurand
# === RAND === nvcc -arch=compute_70 -lcudadevrt -lcudart coredynamics.o patch.o -o patch

#nvcc -arch=compute_70 -Xcompiler -Wall,-pedantic -std=c++11 -O0 -c coredynamics.cu 
#nvcc -arch=compute_70 -Xcompiler -Wall,-pedantic -std=c++11 -O0 -c test.cu 
#nvcc -arch=compute_70 -Xcompiler -Wall,-pedantic test.o coredynamics.o -lcudadevrt -lcudart -o test

#nvcc -arch=compute_61 -rdc=true -Xcompiler -rdynamic -lineinfo -std=c++11 -O0 -c test.cu -o main.o -lcudadevrt
#nvcc -arch=compute_61 -rdc=true -Xcompiler -rdynamic -lineinfo -std=c++11 -O0 -c coredynamics.cu -o coredynamics.o -lcudadevrt
#nvcc -arch=compute_61 main.o coredynamics.o -o test
