#!/bin/bash

optflag=O2
#optflag=g
#gptflag=G
gptflag=lineinfo
cpp_version=c++17

sm=sm_86

rm -f patch.o 
nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -$gptflag -std=$cpp_version -$optflag -c patch.cu

#rm -f coredynamics.o
#nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -$gptflag -std=$cpp_version -$optflag -c coredynamics.cu

#rm -f discrete_convol.o
#nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -lineinfo -std=$cpp_version -$optflag -c discrete_input_convol.cu
##
#rm -f cuda_util.o
#nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -lineinfo -std=$cpp_version -$optflag -c util/cuda_util.cu -o cuda_util.o

rm -f stats.o
nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -std=$cpp_version -$optflag -c stats.cu

#rm -f condShape.o
#nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -std=$cpp_version -$optflag -c condShape.cu

nvcc -arch=$sm -lcudadevrt -lcudart -lboost_filesystem  -lboost_program_options condShape.o patch.o cuda_util.o stats.o discrete_input_convol.o coredynamics.o -$optflag -o $HOME/bin/patch_fast
