#!/bin/bash
module purge
module load gcc/10.2.0
module load cuda/11.1.74
module load boost/intel/1.74.0
module list

cd preprocess

sm=sm_70

rm -f genCon.o
nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -lineinfo -std=c++11 -g -O0 -c genCon.cu

rm -f connect.o
nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -lineinfo -std=c++11 -g -O0 -c connect.cu

rm -f cuda_util.o
nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -lineinfo -std=c++11 -g -O0 -c ../util/cuda_util.cu -o cuda_util.o

nvcc -arch=$sm -lcudadevrt -lcudart -lboost_program_options cuda_util.o connect.o genCon.o -o ../genCon #-lcurand

cd ..
