#!/bin/bash
set -e

fitTC=True
nOri=6
TF=8
SF=17
op=test-s${SF}t${TF}-replay
fdr=$op
lgn=b_4_20-test
v1=replay
v1_cfg=$v1.cfg
lgn_cfg=LGN_V1.cfg
collectMeanDataOnly=False

plotTConly=$1
echo $plotTConly

if [ "$plotTConly" = True ]; then
	fitDataReady=$2
else
	plotOnly=$2
	fitDataReady=True
fi



if [ -d "$fdr" ]
then
	echo overwrite contents in $fdr
else
	mkdir $fdr	
fi
cp $lgn_cfg $v1_cfg $fdr


jobList=""
export plotOnly
export nOri
export TF
export fdr
export op
export lgn
export v1
export v1_cfg
export lgn_cfg
export fitTC
export collectMeanDataOnly
export fitDataReady 

if [ "$plotTConly" = False ]; then
	cp ori.cfg ${op}-ori_1.cfg
	for ori in $( seq 1 $nOri )
	do
		export ori
		jobID=`sbatch --export=ALL ori.slurm`
		jobList="$jobList:${jobID:20}"
	
		if [ "${ori}" -lt "${nOri}" ]; then
			cp ${op}-ori_${ori}.cfg ${op}-ori_$((ori+1)).cfg
			vim -s nextOri_cfg.keys ${op}-ori_$((ori+1)).cfg
		fi
		
	done
	
	sbatch --export=ALL --dependency=afterok$jobList plotTC.slurm
else
	sbatch --export=ALL plotTC.slurm
fi
