#!/bin/bash
module purge
module load all
module load gcc/4.9.3
module load cuda/9.2
module load boost/gcc_4.9.3/openmpi_1.10.2/avx2/1.57.0

cd preprocess 
rm -f retino.o
rm -f dow.o

sm=sm_70

nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -lineinfo -std=c++11 -g -O0 -c retinotopic_connections.cu -o retino.o
nvcc -arch=$sm -rdc=true -Xcompiler -rdynamic -Xptxas -v,-dlcm=cg -lineinfo -std=c++11 -g -O0 -c Dow_et_al_1981.cu -o dow.o

nvcc -arch=$sm -lcudadevrt -lcudart -lboost_program_options retino.o dow.o -o ../retino #-lcurand
cd ..
